db_column_names = [
  "gameID", "gamePlayDate", "gamePlayTime", "gameHomeTeamName", "gameAwayTeamName", "gameHomeTeamID", "gameAwayTeamID",
  "leagueName", "leagueDivisionName", "leagueCompletion", "gameFtScore", "HTS_teamPosition", "HTS_teamGamesPlayed",
  "HTS_teamGamesWon", "HTS_teamGamesDraw", "HTS_teamGamesLost", "HTS_teamGoalsScored", "HTS_teamGoalsConceded",
  "HTS_teamGoalsDifference", "HTS_teamPoints", "HTS_teamPointsPerGame", "HTS_teamPPGlast8", "HTS_teamCleanSheetPercent",
  "HTS_homeGamesWon", "HTS_homeGamesDraw", "HTS_homeGamesLost", "HTS_homeGamesPlayed", "HTS_awayGamesWon", "HTS_awayGamesDraw",
  "HTS_awayGamesLost", "HTS_awayGamesPlayed", "HTS_teamPPGHome", "HTS_teamPPGAway", "HTS_homeGoalMargin_by1_wins",
  "HTS_homeGoalMargin_by1_losses", "HTS_homeGoalMargin_by2_wins", "HTS_homeGoalMargin_by2_losses", "HTS_homeGoalMargin_by3_wins",
  "HTS_homeGoalMargin_by3_losses", "HTS_homeGoalMargin_by4p_wins", "HTS_homeGoalMargin_by4p_losses", "HTS_awayGoalMargin_by1_wins",
  "HTS_awayGoalMargin_by1_losses", "HTS_awayGoalMargin_by2_wins", "HTS_awayGoalMargin_by2_losses", "HTS_awayGoalMargin_by3_wins",
  "HTS_awayGoalMargin_by3_losses", "HTS_awayGoalMargin_by4p_wins", "HTS_awayGoalMargin_by4p_losses", "HTS_totalGoalMargin_by1_wins",
  "HTS_totalGoalMargin_by1_losses", "HTS_totalGoalMargin_by2_wins", "HTS_totalGoalMargin_by2_losses", "HTS_totalGoalMargin_by3_wins",
  "HTS_totalGoalMargin_by3_losses", "HTS_totalGoalMargin_by4p_wins", "HTS_totalGoalMargin_by4p_losses", "HTS_homeGoalsScored",
  "HTS_homeGoalsConceded", "HTS_homeGoalsScoredPerMatch", "HTS_homeGoalsConcededPerMatch", "HTS_homeScored_ConcededPerMatch",
  "HTS_homeOver1_5GoalsPercent", "HTS_homeOver2_5GoalsPercent", "HTS_homeOver3_5GoalsPercent", "HTS_homeOver4_5GoalsPercent",
  "HTS_awayGoalsScored", "HTS_awayGoalsConceded", "HTS_awayGoalsScoredPerMatch", "HTS_awayGoalsConcededPerMatch",
  "HTS_awayScored_ConcededPerMatch", "HTS_awayOver1_5GoalsPercent", "HTS_awayOver2_5GoalsPercent", "HTS_awayOver3_5GoalsPercent",
  "HTS_awayOver4_5GoalsPercent", "HTS_homeCleanSheets", "HTS_homeWonToNil", "HTS_homeBothTeamsScored", "HTS_homeFailedToScore",
  "HTS_homeLostToNil", "HTS_awayCleanSheets", "HTS_awayWonToNil", "HTS_awayBothTeamsScored", "HTS_awayFailedToScore",
  "HTS_awayLostToNil", "HTS_homeScored_ConcededBy_0", "HTS_homeScored_ConcededBy_1", "HTS_homeScored_ConcededBy_2",
  "HTS_homeScored_ConcededBy_3", "HTS_homeScored_ConcededBy_4", "HTS_homeScored_ConcededBy_5p", "HTS_homeScored_ConcededBy_0_or_1",
  "HTS_homeScored_ConcededBy_2_or_3", "HTS_homeScored_ConcededBy_4p", "HTS_awayScored_ConcededBy_0", "HTS_awayScored_ConcededBy_1",
  "HTS_awayScored_ConcededBy_2", "HTS_awayScored_ConcededBy_3", "HTS_awayScored_ConcededBy_4", "HTS_awayScored_ConcededBy_5p",
  "HTS_awayScored_ConcededBy_0_or_1", "HTS_awayScored_ConcededBy_2_or_3", "HTS_awayScored_ConcededBy_4p", "ATS_teamPosition",
  "ATS_teamGamesPlayed", "ATS_teamGamesWon", "ATS_teamGamesDraw", "ATS_teamGamesLost", "ATS_teamGoalsScored", "ATS_teamGoalsConceded",
  "ATS_teamGoalsDifference", "ATS_teamPoints", "ATS_teamPointsPerGame", "ATS_teamPPGlast8", "ATS_teamCleanSheetPercent",
  "ATS_homeGamesWon", "ATS_homeGamesDraw", "ATS_homeGamesLost", "ATS_homeGamesPlayed", "ATS_awayGamesWon", "ATS_awayGamesDraw",
  "ATS_awayGamesLost", "ATS_awayGamesPlayed", "ATS_teamPPGHome", "ATS_teamPPGAway", "ATS_homeGoalMargin_by1_wins",
  "ATS_homeGoalMargin_by1_losses", "ATS_homeGoalMargin_by2_wins", "ATS_homeGoalMargin_by2_losses", "ATS_homeGoalMargin_by3_wins",
  "ATS_homeGoalMargin_by3_losses", "ATS_homeGoalMargin_by4p_wins", "ATS_homeGoalMargin_by4p_losses", "ATS_awayGoalMargin_by1_wins",
  "ATS_awayGoalMargin_by1_losses", "ATS_awayGoalMargin_by2_wins", "ATS_awayGoalMargin_by2_losses", "ATS_awayGoalMargin_by3_wins",
  "ATS_awayGoalMargin_by3_losses", "ATS_awayGoalMargin_by4p_wins", "ATS_awayGoalMargin_by4p_losses", "ATS_totalGoalMargin_by1_wins",
  "ATS_totalGoalMargin_by1_losses", "ATS_totalGoalMargin_by2_wins", "ATS_totalGoalMargin_by2_losses", "ATS_totalGoalMargin_by3_wins",
  "ATS_totalGoalMargin_by3_losses", "ATS_totalGoalMargin_by4p_wins", "ATS_totalGoalMargin_by4p_losses", "ATS_homeGoalsScored",
  "ATS_homeGoalsConceded", "ATS_homeGoalsScoredPerMatch", "ATS_homeGoalsConcededPerMatch", "ATS_homeScored_ConcededPerMatch",
  "ATS_homeOver1_5GoalsPercent", "ATS_homeOver2_5GoalsPercent", "ATS_homeOver3_5GoalsPercent", "ATS_homeOver4_5GoalsPercent",
  "ATS_awayGoalsScored", "ATS_awayGoalsConceded", "ATS_awayGoalsScoredPerMatch", "ATS_awayGoalsConcededPerMatch",
  "ATS_awayScored_ConcededPerMatch", "ATS_awayOver1_5GoalsPercent", "ATS_awayOver2_5GoalsPercent", "ATS_awayOver3_5GoalsPercent",
  "ATS_awayOver4_5GoalsPercent", "ATS_homeCleanSheets", "ATS_homeWonToNil", "ATS_homeBothTeamsScored", "ATS_homeFailedToScore",
  "ATS_homeLostToNil", "ATS_awayCleanSheets", "ATS_awayWonToNil", "ATS_awayBothTeamsScored", "ATS_awayFailedToScore",
  "ATS_awayLostToNil", "ATS_homeScored_ConcededBy_0", "ATS_homeScored_ConcededBy_1", "ATS_homeScored_ConcededBy_2",
  "ATS_homeScored_ConcededBy_3", "ATS_homeScored_ConcededBy_4", "ATS_homeScored_ConcededBy_5p", "ATS_homeScored_ConcededBy_0_or_1",
  "ATS_homeScored_ConcededBy_2_or_3", "ATS_homeScored_ConcededBy_4p", "ATS_awayScored_ConcededBy_0", "ATS_awayScored_ConcededBy_1",
  "ATS_awayScored_ConcededBy_2", "ATS_awayScored_ConcededBy_3", "ATS_awayScored_ConcededBy_4", "ATS_awayScored_ConcededBy_5p",
  "ATS_awayScored_ConcededBy_0_or_1", "ATS_awayScored_ConcededBy_2_or_3", "ATS_awayScored_ConcededBy_4p"
]

analytics_column_names = []
