service: img2palette

provider:
  name: aws
  runtime: python3.7
  stage: local
  region: ${opt:region, 'us-east-1'}
  memorySize: 256
  environment:
    GW_URL:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: "ApiGatewayRestApi"
          - ".execute-api.${self:provider.region}.amazonaws.com/${self:custom.stage}"
    SLS_STAGE: ${self:custom.stage}
    WEBHOOK_PATH: "webhooks/twitter"

package: # Optional deployment packaging configuration
  exclude: # Specify the directories and files which should be excluded in the deployment package
    - .git/**
    - .circleci/**
    - venv/**

plugins:
  - serverless-plugin-select
  - serverless-python-requirements

custom:
  stage: "${opt:stage, self:provider.stage}"
  pythonRequirements:
    dockerizePip: 'non-linux'
    slim: false

functions:
  make_webhook:
    description: Create Twitter webhook
    handler: functions/make_webhook.handler
    stages:
      - prod
  get_webhook:
    description: Get Twitter webhook information
    handler: functions/get_webhook.handler
    stages:
      - prod
  delete_webhook:
    description: Delete Twitter webhook
    handler: functions/delete_webhook.handler
    stages:
      - prod
  make_subscription:
    description: Create Twitter subscription
    handler: functions/make_subscription.handler
    stages:
      - prod
  get_subscription:
    description: Get Twitter webhook information
    handler: functions/get_subscription.handler
    stages:
      - prod
  delete_subscription:
    description: Delete Twitter subscription
    handler: functions/delete_subscription.handler
    stages:
      - prod
  respond_crc:
    description: Respond to Account Activity API CRC 
    handler: functions/respond_crc.handler
    events:
      - http:
          path: ${self:provider.environment.WEBHOOK_PATH}
          method: get
  create_palette:
    description: Create palette and reply to Twitter mentions 
    handler: functions/create_palette.handler
    events:
      - http:
          path: ${self:provider.environment.WEBHOOK_PATH}
          method: post
    stages:
      - prod
    memorySize: 2048
    timeout: 29
  test_create_palette:
    description: Test create palette function
    handler: functions/test_create_palette.handler
    stages:
      - local
  delete_my_status:
    description: Delete bot statuses
    handler: functions/delete_my_status.handler
    stages:
      - local
