version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:erbium-buster
    steps:
      - checkout
      - run:
          name: install pip and venv
          command: |
            sudo apt install python3-pip
            sudo apt install python3-venv
      - run:
          name: install serverless
          command: |
            sudo npm i -g serverless@1.57.0
            npm install
      - run:
          name: set twitter api env variables
          command: |
            echo "CONSUMER_KEY=${CONSUMER_KEY}" >> .env 
            echo "CONSUMER_SECRET=${CONSUMER_SECRET}" >> .env 
            echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> .env 
            echo "ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}" >> .env 
      - run:
          name: deploy serverless
          command: |
            case "$CIRCLE_TAG" in
              prod*)
                STAGE="prod"
                ;;
              test*)
                STAGE="test"
                ;;
            esac
            serverless deploy -s $STAGE

workflows:
  version: 2
  deploy_test:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^test-.+$/
                - /^prod-.+$/
